// Generated by Wrangler on Sun Apr 21 2024 22:23:00 GMT+0900 (日本標準時)
// by running `wrangler types`

interface Env {
    KV1: KVNamespace;
    MY_BROWSER: Fetcher;
    URL_ORIGIN: string | undefined;
}
